"""initial_migration

Revision ID: 3dc96fa39b0b
Revises: 
Create Date: 2026-09-08 23:57:09.669062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc96fa39b0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='management'
    )
    op.create_index(op.f('ix_management_ai_providers_id'), 'ai_providers', ['id'], unique=False, schema='management')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_index(op.f('ix_management_users_email'), 'users', ['email'], unique=True, schema='management')
    op.create_index(op.f('ix_management_users_id'), 'users', ['id'], unique=False, schema='management')
    op.create_index(op.f('ix_management_users_role'), 'users', ['role'], unique=False, schema='management')
    op.create_index(op.f('ix_management_users_username'), 'users', ['username'], unique=True, schema='management')
    op.create_index('ix_users_email_username', 'users', ['email', 'username'], unique=False, schema='management')
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['management.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_index(op.f('ix_management_notes_id'), 'notes', ['id'], unique=False, schema='management')
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('ai_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_id'], ['management.ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_id'], ['management.notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['management.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_index(op.f('ix_management_chat_sessions_id'), 'chat_sessions', ['id'], unique=False, schema='management')
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['management.chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='management'
    )
    op.create_index(op.f('ix_management_chat_messages_id'), 'chat_messages', ['id'], unique=False, schema='management')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_management_chat_messages_id'), table_name='chat_messages', schema='management')
    op.drop_table('chat_messages', schema='management')
    op.drop_index(op.f('ix_management_chat_sessions_id'), table_name='chat_sessions', schema='management')
    op.drop_table('chat_sessions', schema='management')
    op.drop_index(op.f('ix_management_notes_id'), table_name='notes', schema='management')
    op.drop_table('notes', schema='management')
    op.drop_index('ix_users_email_username', table_name='users', schema='management')
    op.drop_index(op.f('ix_management_users_username'), table_name='users', schema='management')
    op.drop_index(op.f('ix_management_users_role'), table_name='users', schema='management')
    op.drop_index(op.f('ix_management_users_id'), table_name='users', schema='management')
    op.drop_index(op.f('ix_management_users_email'), table_name='users', schema='management')
    op.drop_table('users', schema='management')
    op.drop_index(op.f('ix_management_ai_providers_id'), table_name='ai_providers', schema='management')
    op.drop_table('ai_providers', schema='management')
    # ### end Alembic commands ###
