"""setup_user_oauth_cols

Revision ID: de811be83fe3
Revises: 3dc96fa39b0b
Create Date: 2026-09-11 14:43:04.703013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de811be83fe3'
down_revision: Union[str, Sequence[str], None] = '3dc96fa39b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True), schema='management')
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True), schema='management')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True), schema='management')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='management')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='management')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='management')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='management')
    op.drop_column('users', 'avatar_url', schema='management')
    op.drop_column('users', 'oauth_id', schema='management')
    op.drop_column('users', 'oauth_provider', schema='management')
    # ### end Alembic commands ###
